const {webkit}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{const b=await webkit.launch();const p=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[],overflow=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto('http://127.0.0.1:8765');await p.waitForTimeout(500);await p.locator('#startNewMenuBtn').click();await p.locator('#inputStr').fill('ルミナ');await p.locator('#startNewGameBtn').click();await p.waitForTimeout(700);
await p.locator('#faceGachaBtn').click();await p.waitForFunction(()=>!document.getElementById('firstRerollConfirmBtn').disabled);await p.waitForTimeout(1200);await p.screenshot({path:'tests/v3-gacha.png',fullPage:true});await p.locator('#firstRerollConfirmBtn').click();await p.waitForFunction(()=>!window.__firstRerollSelectionPhase);await p.waitForTimeout(500);
await p.evaluate(()=>{window.allowGrowthEvent=false;window.winnerGuessMiniGameEnabled=false;closeAllTopTabs();});await p.locator('#startBattleBtn').click();await p.waitForTimeout(500);assert.equal(await p.evaluate(()=>window.__battleInProgress),false);
async function check(label){const bad=await p.evaluate(()=>{const visible=el=>{if(!el.getClientRects().length)return false;for(let a=el;a;a=a.parentElement){if(a.tagName==='DETAILS'&&!a.open&&a.firstElementChild!==el&&!a.firstElementChild?.contains(el))return false;}return getComputedStyle(el).visibility!=='hidden';};return [...document.querySelectorAll('button,select,input:not(#saveCodeBox),.ability-grid,.character-skill,.ab-loot,summary')].filter(visible).filter(el=>{const r=el.getBoundingClientRect();return r.left< -2||r.right>innerWidth+2||el.clientWidth+3<el.scrollWidth||el.clientHeight+3<el.scrollHeight;}).map(el=>({id:el.id,cls:el.className,text:el.textContent.slice(0,45),w:el.clientWidth,sw:el.scrollWidth,h:el.clientHeight,sh:el.scrollHeight}));});if(bad.length)overflow.push({label,bad});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),true,'page overflow '+label);}
for(const width of [320,375,390,430,844]){await p.setViewportSize({width,height:844});for(const kind of ['char','memory','abyss','guide','log','event','settings']){await p.evaluate(k=>{closeAllTopTabs();toggleTopFold(k)},kind);await p.waitForTimeout(60);if(kind==='char')await p.locator('.character-skills').first().evaluate(el=>el.open=true);if(kind==='guide')await p.locator('.guide-reference').evaluate(el=>el.open=true);await check(width+' '+kind);}}
await p.setViewportSize({width:390,height:844});await p.evaluate(()=>{closeAllTopTabs();toggleTopFold('char')});await p.locator('#charInfoFold').scrollIntoViewIfNeeded();await p.screenshot({path:'tests/v3-character-final.png',fullPage:true});await p.evaluate(()=>{closeAllTopTabs();window.scrollTo(0,0)});await p.waitForTimeout(1800);await p.screenshot({path:'tests/v3-battle-final.png'});
// Reward slot alignment must match the JS itemHeight=36, and awarding remains possible.
await p.evaluate(()=>{toggleTopFold('char');__openWinnerGuessSlotReward({correct:true,amount:10,multiplier:1});});await p.locator('#winnerSlotOverlay').waitFor({state:'visible'});await p.waitForTimeout(1700);await p.screenshot({path:'tests/v3-slot.png'});assert.ok(await p.locator('.winner-slot-modal').evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}),'slot inside visible viewport');await check('slot');for(const el of await p.locator('.winner-slot-lever').all())await el.click();assert.equal(await p.locator('#winnerSlotCloseBtn').isEnabled(),true);await p.locator('#winnerSlotCloseBtn').click();
// Growth dialog actions remain selectable at narrow widths.
await p.setViewportSize({width:320,height:700});await p.evaluate(()=>{__setGrowthDockAutoMode(false);showEventOptions('成長選択',[{label:'攻撃 +100',value:'attack'},{label:'防御 +100',value:'defense'},{label:'速さ +100',value:'speed'}],v=>window.__chosenGrowth=v)});await p.waitForTimeout(200);await check('growth');await p.screenshot({path:'tests/v3-growth.png'});const growthButton=p.locator('#eventPopupOptions button').first();if(await growthButton.isVisible()){await growthButton.click();assert.ok(await p.evaluate(()=>window.__chosenGrowth));}else console.log('growth dock',await p.locator('#growthDockArea').innerText());
await p.evaluate(()=>{clearEventPopup(false);__openTimeUpSummary();});await p.locator('#timeUpSummaryOverlay').waitFor({state:'visible'});await check('timeup');await p.locator('.timeup-summary-close').click();assert.equal(await p.locator('#timeUpSummaryOverlay').isVisible(),false);
assert.deepEqual(errors,[]);console.log('OVERFLOW',JSON.stringify(overflow));assert.deepEqual(overflow,[]);console.log('PASS first gacha / confirmation / real battle / all tabs / slot / growth / responsive');fs.writeFileSync('redesign03-result.json',JSON.stringify({passed:true,widths:[320,375,390,430,844],errors,overflow},null,2));await b.close();})();
